services:
  web:
    build: .
    command: ts-node-dev --respawn --transpile-only src/main.ts
    volumes:
      - .:/app
      - /node_modules:/app/node_modules
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src/web
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

          
