version: '3.7'
services:
  app:
    build: .
    volumes:
      - ./:/usr/src/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    
   