version: '3.7'

services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development
    command: npm run start:debug
